### ISSUE TITLE
dmapp package name

### ISSUE THREAD

**Issue by saatsky** [SkylineCommunications/Low-Code-App-Extensions#1]
Great work,

I would like to suggest case one app is selected to export to include that app name in the dmapp package name.
Case several app are selected to export then dmapp package name can be as is with only the timestamp or appended bundle string. 

The idea behind is the most generic use case, of exporting importing one app, where with just an timestamp might be not enough to distinguish an exported package.

**Comment by ArneMaes0** [comment]
Added the requested feature in release 1.0.0.7
